/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ewidtiwwtvfwflwzynnf"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3aWR0aXd3dHZmd2Zsd3p5bm5mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE5MTU3NTksImV4cCI6MjA4NzQ5MTc1OX0.vWBU30X_g7xhSiguNUy0cZPmjs7S39s6p7-Nw4bfBow"